Repository uncc-hice/edukona_frontend, pull requests merged in 2024-11, with the labels that each got.

#103 Refactor Quiz Deletion with Promise Toast Notification in QuizListRow Component
  src/blocks/QuizListRow.jsx
Labels: pr-description, 0.1.103

#104 Prevent Text Under QR Code from Going Down as the Number of Quiz Participants Increases
  src/pages/QuizSession.jsx
Labels: pr-description, 0.1.104

#105 Add Summary Generation Feature to Customized Menus
  src/blocks/CustomizedMenus.jsx
  src/pages/InstructorRecordings/InstructorRecordings.jsx
Labels: pr-description, 0.1.105, 0.1.105.1, 0.1.105.2, 0.1.105.3, 0.1.105.4

#107 Add GenericMenu Component
  src/blocks/GenericMenu.jsx
Labels: pr-description

#112 # Create EditableQuestion Component
  src/blocks/EditableQuestion.jsx
Labels: pr-description

#110 Enhance Incorrect Answers Display in EditQuizView
  src/pages/EditQuizView.jsx
Labels: pr-description, 0.1.110

#114 Refactor and Simplify EditQuizView Component
  src/pages/EditQuizView.jsx
Labels: pr-description, 0.1.114

#115 Refactor QuizList Component and Extract API Service
  src/blocks/QuizList.jsx
  src/blocks/QuizListRow.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.115

#117 Refactor Quiz Title Update Logic to Use Service Function
  src/blocks/ChangeQuizTitleDialog.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.117

#116 Fix API Endpoint URLs for Recordings
  src/blocks/RecordButton.jsx
  src/pages/InstructorRecordings/InstructorRecordings.jsx
Labels: pr-description, 0.1.116

#118 Enhance API Response Handling with Interceptor for Unauthorized Access
  src/services/apiService.js
Labels: pr-description

#120 Refactor Quiz Application: Update Quiz Title Mechanism and API Integration
  src/blocks/ChangeQuizTitleDialog.jsx
  src/blocks/QuizListRowMenu.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.120

#122 Implement Summary Feature in Application
  package-lock.json
  package.json
  src/App.js
  src/blocks/SummaryEditor.jsx
  src/blocks/SummaryViewer.jsx
  src/pages/Summary.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.122, 0.1.122.1, 0.1.122.2

#121 Enhance AnswerOption Component with Highlight Features and Animations
  src/blocks/AnswerOption.jsx
  src/blocks/AnswersGrid.jsx
  src/blocks/QuizComponent.jsx
  src/blocks/StudentAnswersGrid.jsx
  src/pages/InstructorQuestionView.jsx
Labels: pr-description, 0.1.121, 0.1.121.1, 0.1.121.2, 0.1.121.3

#123 Enhance Quiz and Recording List UI to Handle Empty States
  package-lock.json
  src/blocks/QuizList.jsx
  src/pages/InstructorRecordings/InstructorRecordings.jsx
Labels: pr-description, 0.1.123

#127 Refactor Student Answer Components for Improved State Management
  src/blocks/StudentAnswersGrid.jsx
  src/pages/StudentAnswerView.jsx
Labels: pr-description, 0.1.127, 0.1.127.1

#125 # Refactor Quiz Results Fetching Logic
  src/pages/QuizSessionResults.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.125, 0.1.125.1, 0.1.125.2, 0.1.125.3, 0.1.125.4

#119 Update Routing Logic and Improve SignUp Process
  src/App.js
  src/blocks/Functions.js
  src/blocks/SignUpForm.js
  src/services/apiService.js
Labels: pr-description, 0.1.119, 0.1.119.1, 0.1.119.2, 0.1.119.3, 0.1.119.4

#128 Enhance Error Handling Across Quiz and Summary Components
  src/blocks/QuizList.jsx
  src/blocks/SignUpForm.js
  src/pages/InstructorRecordings/InstructorRecordings.jsx
  src/pages/Summary.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.128, 0.1.128.1

#124 # Refactor Instructor Recordings Feature
  src/pages/InstructorRecordings/InstructorRecordings.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.124, 0.1.124.1, 0.1.124.2, 0.1.124.3, 0.1.124.4, 0.1.124.5, 0.1.124.6, 0.1.124.7, 0.1.124.8

#132 Refactor Profile Fetching Logic and Introduce Toast Notifications
  src/pages/ProfilePage/General/General.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.132

#130 Remove YourSessions Page and Navigation
  src/App.js
  src/layouts/Dashboard/components/components/SidebarNav.js
  src/pages/YourSessions.jsx
Labels: pr-description, 0.1.130

#129 Refactor Account Deletion Process in Security Component
  src/pages/ProfilePage/Security/Security.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.129, 0.1.129.1, 0.1.129.2, 0.1.129.3

#133 feat: Add ESLint and TypeScript Configuration, Create EditRecordingTitleDialog Component
  .github/workflows/eslint.yml
  eslint.config.mjs
  package-lock.json
  package.json
  src/App.test.js
  src/blocks/DeleteQuestionDialog.jsx
  src/blocks/LoginForm.js
  src/blocks/QuizListRow.jsx
  src/blocks/SignUpForm.js
  src/blocks/Timer.js
  src/pages/InstructorQuestionView.jsx
  src/pages/InstructorRecordings/Components/EditRecordingTitleDialog.tsx
  tsconfig.json
Labels: pr-description, 0.1.133

#134 KAN-219: Add Delete Recording Dialog Component
  src/blocks/DeleteRecordingDialog.jsx
  src/pages/InstructorRecordings/InstructorRecordings.jsx
Labels: pr-description, 0.1.134, 0.1.134.1

#137 KAN-182: Introduction of Basic Server Configuration and Environment Setup
  .ebignore
  Procfile
  package-lock.json
  package.json
  server.js
Labels: pr-description, 0.1.137, 0.1.137.1, 0.1.137.2

#139 KAN-221: Create New Quiz Dialog Component
  src/blocks/NewQuizDialog.tsx
  src/index.css
  src/services/lambdaService.js
Labels: pr-description, 0.1.139

#142 Refactor DeleteRecordingDialog Placement in InstructorRecordings Component
  src/pages/InstructorRecordings/InstructorRecordings.jsx
Labels: pr-description, 0.1.142

#140 KAN-226: Refactor CustomizedMenus and InstructorRecordings components
  src/pages/InstructorRecordings/InstructorRecordings.jsx
Labels: pr-description, 0.1.140, 0.1.140.1, 0.1.140.2

#143 Refactor Quiz Creation and Settings Management
  src/pages/CreateQuiz.jsx
  src/pages/InstructorQuestionView.jsx
  src/pages/SettingsPage/Settings.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.143
