Repository uncc-hice/edukona_frontend, pull requests merged in 2024-12, with the labels that each got.

#141 KAN-188: Refactor and Improve Quiz Creation Feature
  .github/workflows/deploy-to-prod.yml
  eslint.config.mjs
  src/blocks/NewQuizDialog.tsx
  src/pages/InstructorQuestionView.jsx
  src/pages/InstructorRecordings/InstructorRecordings.jsx
  tsconfig.json
Labels: pr-description, 0.1.141, 0.1.141.1, 0.1.141.2

#144 KAN-222: Implement Recording List Row Menu with Action Dialogs
  src/blocks/DeleteRecordingDialog.jsx
  src/blocks/RecordingListRowMenu.tsx
  src/pages/InstructorRecordings/Components/EditRecordingTitleDialog.tsx
  src/pages/InstructorRecordings/InstructorRecordings.jsx
  src/services/apiService.js
  src/services/lambdaService.js
  src/types/edukonaTypes.ts
Labels: pr-description, 0.144.1, 0.1.144.2

#145 Add JWT User Context for Authentication Management
  src/JWTUserContext.tsx
  src/services/apiService.js
Labels: pr-description, 0.1.145

#146 Enhance JWT Authentication Flow with New User Context and Login Form
  src/App.js
  src/JWTUserContext.tsx
  src/blocks/JWTLoginForm.tsx
  src/services/apiService.js
Labels: pr-description, 0.1.146, 0.1.146.1
