Repository uncc-hice/edukona_frontend, pull requests merged in 2025-01, with the labels that each got.

#147 Refactor Contact Form Submission to Use API Service
  src/pages/Landing/components/Contact/Contact.js
  src/services/apiService.js
Labels: pr-description, 0.1.147, 0.1.147.1

#149 Enhance JWT Authentication with Signup Functionality
  src/App.js
  src/JWTUserContext.tsx
  src/blocks/JWTSignUpForm.tsx
  src/services/apiService.js
  src/styles/SignUpForm.css
Labels: pr-description, 0.1.149, 0.1.149.1, 0.1.149.2

#151 KAN-261: Enhance JWT Authentication and User Context Management
  src/App.js
  src/JWTUserContext.tsx
  src/UserContext.js
  src/index.js
  src/layouts/Main/components/Topbar/Topbar.js
  src/services/apiService.js
Labels: pr-description, 0.1.151

#148 Add AccordionQuizzes Component for Recording Quizzes
  src/pages/InstructorRecordings/Components/AccordionQuizzes.tsx
  src/pages/InstructorRecordings/InstructorRecordings.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.148, 0.1.148.1, 0.1.148.2

#155 KAN-269: Refactor InstructorQuestionView: Quiz State Management Improvement
  src/pages/InstructorQuestionView.jsx
Labels: pr-description, 0.1.155

#152 # Refactor DeleteQuestionDialog to Use API Service
  src/blocks/DeleteQuestionDialog.jsx
  src/blocks/EditableQuestion.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.152, 0.1.152.1

#153 Refactor Quiz Management Functions to Use API Service
  src/blocks/QuizListRow.jsx
  src/pages/EditQuizView.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.153, 0.1.153.1

#156 Fix/misc calls to api service
  src/blocks/BarGraphContainer.jsx
  src/blocks/EditableQuestion.jsx
  src/blocks/RecordButton.jsx
  src/pages/QuizSession.jsx
  src/services/apiService.js
Labels: 0.1.156

#157 Refactor WebSocket Connections to Custom Hooks
  src/pages/InstructorQuestionView.jsx
  src/pages/InstructorRecordings/InstructorRecordings.jsx
  src/pages/JoinQuiz.jsx
  src/pages/QuizSession.jsx
  src/pages/StudentAnswerView.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.157, 0.1.157.1

#158 Enhance Authentication Handling in Lambda Service
  src/services/apiService.js
  src/services/lambdaService.js
Labels: pr-description, 0.1.158, 0.1.158.1

#159 KAN-240: Refactor AccordionQuizzes component and implement RecordingListRow
  src/pages/InstructorRecordings/Components/AccordionQuizzes.tsx
  src/pages/InstructorRecordings/Components/RecordingListRow.tsx
  src/pages/InstructorRecordings/InstructorRecordings.jsx
Labels: pr-description, 0.1.159, 0.1.159.1

#163 KAN-285: Remove Settings Page and Related References
  src/App.js
  src/blocks/QuizListRowMenu.jsx
  src/pages/SettingsPage/Settings.jsx
  src/pages/SettingsPage/SettingsPage.css
Labels: pr-description, 0.1.163

#162 KAN-289: Refactor AccordionQuizzes Component
  src/pages/InstructorRecordings/Components/AccordionQuizzes.tsx
Labels: pr-description, 0.1.162, 0.1.162.1

#164 KAN-280: Create Course Selection Menu
  src/App.js
  src/InstructorContext.tsx
  src/components/CourseDropdown/CourseDropdown.tsx
  src/components/CourseDropdown/index.tsx
  src/index.js
  src/layouts/Main/components/Topbar/Topbar.js
  src/pages/InstructorRecordings/InstructorRecordings.jsx
  src/services/apiService.js
  src/types/edukonaTypes.ts
Labels: pr-description, 0.1.164, 0.1.164.1, 0.1.164.2

#161 Add Storybook Configuration and Component Documentation
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/pages/InstructorRecordings/Components/AccordionQuizzes.stories.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: pr-description, 0.1.161

#166 Update Feedback Typography in AnswerOption Component
  src/blocks/AnswerOption.jsx
Labels: pr-description, 0.1.166
