Repository uncc-hice/edukona_frontend, pull requests merged in 2025-03, with the labels that each got.

#173 Enhance Quiz Actions Menu Interaction
  src/blocks/QuizListRowMenu.jsx
Labels: pr-description, 0.1.173

#174 KAN-307: Add Recording Duration Component and Update Recording List
  src/pages/InstructorRecordings/Components/RecordingDuration.tsx
  src/pages/InstructorRecordings/Components/RecordingListRow.tsx
  src/pages/InstructorRecordings/InstructorRecordings.jsx
  src/types/edukonaTypes.ts
Labels: pr-description, 0.1.174

#171 KAN-274: Refactor QuizEndView Component to TypeScript and Enhance Functionality
  src/pages/InstructorQuestionView.jsx
  src/pages/QuizEndView.jsx
  src/pages/QuizEndView.tsx
  src/pages/StudentAnswerView.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.171, 0.1.171.1, 0.1.171.2

#175 ## Improve Error Handling and Token Management
  src/InstructorContext.tsx
  src/JWTUserContext.tsx
  src/hooks/useWebSocketWithTokenRefresh.ts
  src/pages/InstructorRecordings/InstructorRecordings.jsx
  src/services/apiService.js
Labels: pr-description, 0.1.175

#176 # Enhance Recording List with Transcript Download Functionality
  src/blocks/RecordingListRowMenu.tsx
  src/services/apiService.js
Labels: pr-description, 0.1.176

#179 [KAN-306] Add Change Course Functionality to Recording List
  src/blocks/RecordingListRowMenu.tsx
  src/pages/InstructorRecordings/Components/ChangeRecordingCourseDialog.tsx
  src/services/apiService.js
  src/types/edukonaTypes.ts
Labels: pr-description, 0.1.179

#180 KAN-283: Refactor StudentAnswerView Component to Remove Skip Power Up Functionality
  src/pages/StudentAnswerView.jsx
Labels: pr-description, 0.1.180, 0.1.180.1

#183 [KAN-320] Enhance Editable Question Component Layout
  src/blocks/EditableQuestion.jsx
Labels: pr-description, 0.1.183

#177 [KAN-287] Enhance Google Login Functionality
  .github/workflows/deploy-eb.yml
  src/JWTUserContext.tsx
  src/blocks/JWTLoginForm.tsx
  src/blocks/JWTSignUpForm.tsx
  src/services/apiService.js
Labels: pr-description, 0.1.177, 0.1.177.1, 0.1.177.2, 0.1.177.3, 0.1.177.4
