Repository uncc-hice/edukona_frontend, pull requests merged in 2025-02, with the labels that each got.

#170 Team Page Update
  src/pages/Team/Team.js
Labels: 0.1.170, 0.1.170.1

#160 Enhance Navbar with JWT Logout and Implement WebSocket Token Refresh Mechanism
  src/JWTUserContext.tsx
  src/blocks/Navbar.jsx
  src/hooks/useWebSocketWithTokenRefresh.ts
  src/services/apiService.js
Labels: pr-description, 0.1.160, 0.1.160.1, 0.1.160.2, 0.1.160.3, 0.1.160.4

#172 KAN-286: Refactor Mock Service Worker and Menu Components
  public/mockServiceWorker.js
  src/blocks/GenericMenu.jsx
  src/blocks/RecordingListRowMenu.tsx
  src/stories/Configure.mdx
  tsconfig.json
Labels: pr-description, 0.1.172

#165 KAN-292: Enhance Course Management with Create Course Feature
  package-lock.json
  package.json
  src/InstructorContext.tsx
  src/blocks/EditableQuestion.jsx
  src/components/CourseDropdown/CourseDropdown.tsx
  src/components/CourseDropdown/CreateCourseDialog/CreateCourseDialog.tsx
  src/components/CourseDropdown/CreateCourseDialog/index.tsx
  src/components/LocalizedDatePicker/LocalizedDatePicker.tsx
  src/components/LocalizedDatePicker/index.tsx
  src/services/apiService.js
Labels: pr-description, 0.1.165, 0.1.165.1, 0.1.165.2, 0.1.165.3, 0.1.165.4
